# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-GB"
title: "Chattertots"
title_separator: " - "
#subtitle: "Speech and Language Therapy"
email: chattertots@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chattertots is run by Louise Hibbert, a fully qualified Speech and Language Therapist who specialises in working with children aged approximately 2 to 8 years.
url: https://chattertots.github.io
baseurl: "/"
repository: "chattertots/chattertots.github.io"
twitter:
  username: chattertots
github:
  username: chattertots
facebook:
    username : chattertots
    appid: 2220287517999610
og_image: "/assets/images/louise-hibbert.jpg"
minimal_mistakes_skin: default
search: true
incremental: true
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages
  - .htaccess
  - google19375e3e49844e36.html
  - favicon.ico
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .env 
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name   : "Louise Hibbert"
  avatar : "/assets/images/louise-hibbert.jpg"
  bio    : "Chattertots is run by Louise Hibbert, a fully qualified Speech and Language Therapist who specialises in working with children aged approximately 2 to 8 years."
  location : "Hydestile, Surrey"
  links:
    - label: "Phone"
      icon: "fab fa-fw fa-phone-square"
      url: "tel:+441483389949"
    - label: "Email"
      icon: "fab fa-fw fa-envelope-square"
      url: "mailto:chattertots@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/chattertots"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/chattertots"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

footer:
  links:
    - label: "Phone"
      icon: "fab fa-fw fa-phone-square"
      url: "tel:+441483389949"
    - label: "Email"
      icon: "fab fa-fw fa-envelope-square"
      url: "mailto:chattertots@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/chattertots"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/chattertots"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

comments:
  provider: "facebook"
  facebook:
    appid: 2220287517999610
    num_posts: 5 
    colorscheme: "light"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-32275738-1"
    anonymize_ip: false # default

bing_site_verification: "7EC46C49A65108BC90660DF188AD1F53"

google-site-verification: google19375e3e49844e36.html

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
